apiVersion: v2
name: spark
description: A Helm chart for Spark Social Media Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - social-media
  - dating
  - web-application
home: https://github.com/Kwatu05/spark
sources:
  - https://github.com/Kwatu05/spark
maintainers:
  - name: Kwatu05
    email: admin@spark.com
dependencies:
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
